# Generated by Django 4.2 on 2025-11-20 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SonaStudySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('experiment_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('timeslot_id', models.IntegerField(blank=True, null=True)),
                ('timeslot_date', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('num_signed_up', models.IntegerField(blank=True, null=True)),
                ('num_students', models.IntegerField(blank=True, null=True)),
                ('researcher_id', models.IntegerField(blank=True, null=True)),
                ('survey_flag', models.IntegerField(blank=True, null=True)),
                ('web_flag', models.IntegerField(blank=True, null=True)),
                ('videoconf_flag', models.IntegerField(blank=True, null=True)),
                ('videoconf_url', models.URLField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'start_time', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='labassistant',
            options={},
        ),
        migrations.RemoveField(
            model_name='labassistant',
            name='status',
        ),
        migrations.AddField(
            model_name='labassistant',
            name='is_schedule_assistant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labassistant',
            name='role',
            field=models.CharField(choices=[('ra', 'Research Assistant'), ('scheduling_admin', 'Scheduling Admin'), ('full_admin', 'Full Admin')], default='ra', max_length=20),
        ),
        migrations.AlterField(
            model_name='labassistant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.AddField(
            model_name='sonastudyschedule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_studies', to='accounts.labassistant'),
        ),
    ]
